[package]
name = "rensa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rensa"
crate-type = ["cdylib"]

[dependencies]
fxhash = "0.2.1"
murmurhash3 = "0.0.5"
pyo3 = "0.21.1"
rand = "0.8.5"
