[package]
name = "rensa"
version = "0.2.0"
edition = "2021"
authors = ["Luis Cardoso <luis@luiscardoso.dev>"]
description = "High-performance MinHash implementation in Rust with Python bindings for efficient similarity estimation and deduplication of large datasets"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/beowolx/rensa"
keywords = ["minhash", "lsh", "similarity", "deduplication", "data-mining"]
categories = [
  "algorithms",
  "data-structures",
  "science",
  "text-processing",
  "database-implementations",
]

[lib]
name = "rensa"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.1"
rand = "0.9.0"
rustc-hash = "2.1.1"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
